### ISSUE TITLE
Emulator sources?

### ISSUE THREAD

**Issue by Spritetm** [leeseungcheol/ODROID-GO#7]
It seems that the Odroid-Go uses Gnuboy, SMSPlus and Nofrendo as its emulators (as can be seen in the firmware package: https://www.dropbox.com/s/8e89fiv810ba9vl/odroid-go-firmware-bin-2018-05-14.tgz ). These emulators are all licensed under the GPL. Can you share the sources to these? (I'd create an issue in the official Odroid repo, but it does not allow issues to be created.)

**Comment by leeseungcheol** [comment]
You can see the source code at https://github.com/OtherCrashOverride/go-play
We will upload related content including esp-idf build tutorial to the wiki during the next week.

Thank you.

**Comment by Spritetm** [comment]
Ah cool, did not see that. Thanks!
