### ISSUE TITLE
Display Driver Bug

### ISSUE THREAD

**Issue by Kabron287** [leeseungcheol/ODROID-GO#8]
There is a definite bug in display driver(due to display model) which causes mirrored output in some cases. 
To test it run the following:
  **GO.begin();
  GO.lcd.setRotation(0);
  GO.lcd.fillScreen(TFT_BLACK);
  GO.lcd.println("Hello World!!!");**

to correct the bug, the following code in **Display.cpp**

    **writecommand(ILI9341_DFUNCTR); // Display Function Control
    writedata(0x08);
    writedata(0x82);
    writedata(0x27);**

need to be replaced with

   **writecommand(ILI9341_DFUNCTR); // Display Function Control
    writedata(0x0A);
    writedata(0xA2);
    writedata(0x27);**

**Comment by leeseungcheol** [comment]
Thank you for the issue.
I will test it!
